<template>
  <mailing-message
    :title="$t('Success')"
    :text="$t('Changed_Successfully')"
    :button-text="$t('Login')"
    image="checked.png"
    url="login"
  ></mailing-message>
</template>
