<template>
  <mailing-message
    :title="$t('Success')"
    :text="$t('ChangedSuccessfully')"
    :button-text="$t('LogIn')"
    image="checked.png"
    url="login"
  ></mailing-message>
</template>
