<template>
  <mailing-message
    :title="$t('Thank_You')"
    :text="$t('Instructions_Sent')"
    :button-text="$t('Go_Home')"
    image="upArrow.png"
    url="home"
  ></mailing-message>
</template>
